sudo: false
dist: xenial
language: ruby
cache: bundler
rvm:
- 2.5.3
env:
  global:
  - SFTP_USER=ieo2
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
jobs:
  include:
  - stage: Test
    script:
    - JEKYLL_ENV=production bundle exec jekyll build
  - stage: Github Release
    script:
    - JEKYLL_ENV=production bundle exec jekyll build
before_install:
- openssl aes-256-cbc -K $encrypted_9d525edf3d79_key -iv $encrypted_9d525edf3d79_iv
  -in meme.pem.enc -out /tmp/meme.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/meme.pem
- ssh-add /tmp/meme.pem
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -e "ssh -o \"StrictHostKeyChecking=no\"" --quiet $TRAVIS_BUILD_DIR/_site $SFTP_USER@linux.cefns.nau.edu:/home/ieo2/public_html/test_site/
  on:
    branch: travis-dev
