sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
bundler_args: --without development
install: gem install github-pages
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
jobs:
  include:
    - stage: Test
      script:
        - JEKYLL_ENV=production jekyll build
    - stage: Github Release
      script:
        - JEKYLL_ENV=production jekyll build
