theme: jekyll-theme-cayman
baseurl: /capstone/projects/CS/2020/EnginAir-S20/
repository: EnginAir/enginair.github.io
title: EnginAir
description: EnginAir is a web-app designed to help Honeywell determine where Wi-Fi is needed most for its CEDAS systems.
