markdown:         kramdown
highlighter:      rouge

theme: jekyll-theme-hydeout
baseurl: /capstone/projects/CS/2020/EnginAir-S20
repository: EnginAir/enginair.github.io
title: EnginAir
tagline: A Capstone Project
description: A capstone project
lang: en
timezone: America/Phoenix

author:
  name: 'EnginAir'
  url: https://cefns.nau.edu/capstone/projects/CS/2020/EnginAir-S20/

